version: 2.1

orbs:
  python: circleci/python@2.0.3

workflows:
  run-tests:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              python-version: [ "3.10", "3.11", "3.12" ]


jobs:
  build-and-test:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Ruff lint
          command: ruff check .
      - run:
          name: Ruff Format
          command: ruff format . --check
      - run:
          name: Run tests
          command: pytest
